
export const Hotkeys={
    Snap:{
        Preset_1:'0.0'
    },
    NetTool:{
        NetToolLine:'1.0',
        LevelUp:'1.1',
        LevelDown:'1.2',
    },
    HomeSaveTypes:{
        Home:'2.0'
    },
    ToolsSide:{
        Flow:{
            '+':'3.0',
            '-':'3.1',
            'indicator':'3.4',
        },
        Radius:{
            '-':'3.2',
            '+':'3.3',
            'indicator':'3.5',
        },
        Range:{
            '+':'3.6',
            '-':'3.7',
        },
        Strength:{
            '-':'3.8',
            '+':'3.9',
        },
        ReplaceTreeAge:'3.10',
        Replace:'3.11',
        PlaceMode:{
            'Point':'3.12',
            'Straight':'3.13',
            'SimpleCurve':'3.14',
            'Circle':'3.15',
        },
        Spacing:{
            '-':'3.16',
            '+':'3.17',
        },
        Rotate:{
            '-':'3.18',
            '+':'3.19',
        },
        Theme:{
            'European':'3.20',
            'American':'3.21',
        },
        PrefabType:'3.22',
        Type:{
            'TreesDeciduous':'3.23',
            'TreesNeedle':'3.24',
            'Bushes':'3.25',
            '1':'3.26',
            '2':'3.27',
            '3':'3.28',
            '4':'3.29',
            '5':'3.30',
        },
        Age:{
            'AllYYTC':'3.31',
            'Sapling':'3.32',
            'Teen':'3.33',
            'Adult':'3.34',
            'Elderly':'3.35',
            'Dead':'3.36',
        }
    },
    InfoPanel:{
        ClosePanel:'4.0',
        AlwaysClosePanel:'4.1',
    },
    MouseHighlight:{
        PrintElements:'5.0',
    },
    Editor:{
        Probability:'6.0',
        ParentGrid:'6.1',
    },
    DebugPanel:{
        Console:'7.0'
    }
};
